 <?php
//SECURE LOGIN / BY / LVXWEB / OPENSOURCE / PROJECT / PHP / MYSQL / COOKIE /CONTACT: LVXWEB96@PROTONMAIL.COM//
define ("HOST", "HOSTNAME"); //IL VS HOST NEL SECONDO CAMPO.
define ("USER", "USERNAME"); //USERNAME NEL SECONDO CAMPO.
define ("PASSWORD", "PASS"); //LA VS PASS DI DATABASE NEL SECONDO CAMPO.
define ("DATABASE", "DB_NAME"); //NOME DEL VOSTRO DATABASE, NEL SECONDO CAMPO.


//PERMESSI//
define ("CAN_REGISTER", "ANY");
define ("DEFAULT_ROLE", "member");


//SSL//
define ("SECURE", "FALSE"); //IMPOSTARE TRUE IN CASO DI CERTIFICATO SSL.
